apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: my-app
spec:
  type: ClusterIP
  clusterIP: None
  clusterIPs:
  - None
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  selector:
    service: api
    app: api
  ports:
    - name: tcp-api-int
      protocol: TCP
      port: 3000
      targetPort: tcp-api-int
  sessionAffinity: None