apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: my-app
  labels:
    service: api
    app: api
spec:
  replicas: 2
  selector:
    matchLabels:
      service: api
      app: api
  template:
    metadata:
      labels:
        service: api
        app: api
    spec:
      containers:
        - name: api
          image: athsilva/k8s-api:latest
          env:
            - name: KAFKA
              value: kafka-headless.my-app:9092
            - name: KAFKA_TOPIC
              value: k8s-topic
          ports:
            - name: tcp-api-int
              containerPort: 3000
              protocol: TCP
      restartPolicy: Always
      dnsPolicy: ClusterFirst
