apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: init-kafka
  name: init-kafka
  namespace: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init-kafka
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: init-kafka
    spec:
      containers:
        - args:
            - |2
              # blocks until kafka is reachable
              kafka-topics --bootstrap-server kafka-headless.my-app.svc.cluster.local:9092 --list

              echo -e 'Creating kafka topics'
              kafka-topics --bootstrap-server kafka-headless.my-app.svc.cluster.local:9092 --create --if-not-exists --topic my-first-topic --replication-factor 1 --partitions 1
              kafka-topics --bootstrap-server kafka-headless.my-app.svc.cluster.local:9092 --create --if-not-exists --topic k8s-topic --replication-factor 1 --partitions 1

              echo -e 'Successfully created the following topics:'
              kafka-topics --bootstrap-server kafka-headless.my-app.svc.cluster.local:9092 --list
          command:
            - /bin/sh
            - -c
          image: confluentinc/cp-kafka:6.1.1
          name: init-kafka
      restartPolicy: Always
